### ISSUE TITLE
注册表单昵称和密码不应该预置，昵称、专业、电话没有设置为必填，没有数据时会注册失败

### ISSUE THREAD

**Issue by SeinoNana** [EyesCMS/zhishe-cms-web#111]
![image](https://user-images.githubusercontent.com/50039165/83230877-203d4a80-a1bd-11ea-93e3-8ef8e094693c.png)

**Comment by xjliang** [comment]
最新的注册表单 https://eyescms.github.io/zhishe-cms-doc/zh/api/#_2-3-注册

**Comment by 221701323** [comment]
已经修改了注册的方式
