### ISSUE TITLE
社团详情页面建议美化

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#14]
![image](https://user-images.githubusercontent.com/46876506/81185152-d01b0000-8fe3-11ea-8cca-798edd6e0802.png)

**1. 单独一个头像占据一行，有点怪**
**2. 建议头像居中，表单也居中，表单信息输入框去掉**
**3. 在一页内信息全部信息**

**Comment by xjliang** [comment]
![image](https://user-images.githubusercontent.com/46876506/81188638-28ec9780-8fe8-11ea-94f4-e4fc69c2a80a.png)

可以参考一下

**Comment by is-lyx** [comment]
暂定初版，如果还需要改动可以再改
