### ISSUE TITLE
表单死数据：解散社团和社团换届

### ISSUE THREAD

**Issue by yz990219** [EyesCMS/zhishe-cms-web#27]
![图片](https://user-images.githubusercontent.com/50985454/81316602-5ad02d80-90be-11ea-95f2-4f9acd497a9c.png)
![图片](https://user-images.githubusercontent.com/50985454/81316628-66bbef80-90be-11ea-90fe-b9f8714c29d2.png)
还有就算换届我按照死数据用了可行的表单数据但是还是没办法提起申请，这块是不是还没做完啊

**Comment by is-lyx** [comment]
死数据和换届已修复。原本换届提交失败有两种情况，一种返回400是因为已提交过，管理员待审核（但是messagebox没有显示，这个后面还要调整一下），另一种是前端代码里面对返回status判断写成了Status，所以导致无论提交成不成功都跳去else的修改失败。已修改
