### ISSUE TITLE
很多页面的图片点击后，页面卡住不动了（滚动条消失）

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#30]
浏览器：Chrome 和 Firefox 都有该问题，应该不是浏览器问题

**Comment by is-lyx** [comment]
原来element-ui的版本号为2.13.0存在这个bug。在项目package.json中修改element-ui的版本号为2.13.1即可，此bug在2.13.1已修复，重新npm install等操作就可以解决
