### ISSUE TITLE
学生申请社团创建：步骤条在表单提交后没有改变 active index（0 -> 1）

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#32]
![image](https://user-images.githubusercontent.com/46876506/81359846-df499d00-910c-11ea-9ce2-7964a0f79812.png)

```
if (this.active++ > 2) this.active = 0;
```

另外，界面应该切换为提示已提交，而不是提留在表单填写界面
例如：页面直接提示为：**您已提交，请等待管理员审核!**

**Comment by is-lyx** [comment]
已添加
