### ISSUE TITLE
与后端对接走马灯图片接口

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#44]
1. 上传走马灯图片
2. 社团页面设置走马灯图片（目前是使用静态图片资源）

**Comment by xjliang** [comment]
可以把社团相册内的图片作为走马灯图片

**Comment by SeinoNana** [comment]
修改如下：
1.完成了走马灯图片的上传
2.完成了社团页面设置走马灯图片
3.若未上传走马灯图片或者上传的走马灯图片数量小于3张，会使用静态图片资源进行补充
