### ISSUE TITLE
社团相册上传 5 张后，没有提示不能继续上传

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#60]
![image](https://user-images.githubusercontent.com/46876506/82773946-0545a000-9e76-11ea-84e1-b6c2aee08bfc.png)

**Comment by SeinoNana** [comment]
修改如下：
![image](https://user-images.githubusercontent.com/50039165/82802169-08aa4d00-9eb1-11ea-9cc4-1a287cfd3d19.png)

![image](https://user-images.githubusercontent.com/50039165/82802152-0516c600-9eb1-11ea-9790-a748799fe162.png)
