### ISSUE TITLE
轮播图图片大小格式不同，展示效果差

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#61]
![image](https://user-images.githubusercontent.com/46876506/82774065-55246700-9e76-11ea-8a73-aae3f825ddaa.png)

**Comment by SeinoNana** [comment]
修改如下：
![image](https://user-images.githubusercontent.com/50039165/82870489-a1e56c00-9f62-11ea-918b-26403fab2e27.png)
