### ISSUE TITLE
帖子页面：通过 Url  添加图片没有直接上传图片，没有传图片还会有个占位符

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#63]
![image](https://user-images.githubusercontent.com/46876506/82774384-412d3500-9e77-11ea-9f93-72e5f540f874.png)

**Comment by 221701323** [comment]
没有图片的时候已经不会显示占位符了，但是当imgUrl有值，但是在该路径下没有图片的时候还是会有占位符，看是否关闭
