### ISSUE TITLE
查看评论多次请求、建议可以下拉和收起

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#9]
![image](https://user-images.githubusercontent.com/46876506/81181261-c642ce00-8fde-11ea-8663-27a8fda87e43.png)

**点一次就发一次请求，能不能做弹出一下，再收回去，用户第一次可以弹出，就自然会试试收回，然后一直点**

**Comment by 221701323** [comment]
已经能够在页面生成阶段就有评论信息了，也有收起功能
