### ISSUE TITLE
某些页面可以修改成延迟加载：等用户点击后再发送请求，如活动论坛页面

### ISSUE THREAD

**Issue by xjliang** [EyesCMS/zhishe-cms-web#95]

**Comment by xjliang** [comment]
![image](https://user-images.githubusercontent.com/46876506/83272408-b1341600-a1fd-11ea-9274-00e867b6ea48.png)

这个可以从活动论坛的评论列表开始，评论列表默认设置为收起

**Comment by 221701323** [comment]
评论已经默认收起了
